### PR TITLE
Add support for filtering by type

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by totten** [comment]
@colemanw nice

**Comment by totten** [comment]
I mean -- it's got updates to code and tests and docs -- all at once! Hoowa!

**Comment by JoeMurray** [comment]
Very nice.

However, I think we normally provide sample ways to adjust settings in civicrm.settings.php by providing a commented out line of what should be done to enable / override a setting. Could you put something like that into the template for civicrm.settings.php ?

Also, could you perhaps update the wiki documentation for installation, anything else that is relevant?

**Comment by colemanw** [comment]
@JoeMurray I've added https://github.com/civicrm/civicrm-core/pull/8763
Not sure about where we might put this in the wiki.

**Pull request merged**
